acco/urls.py
from django.urls import path
from .views import SignUpView, SignSuccessView
from django.contrib.auth.views import LoginView, LogoutView
# from django.views.generic import RedirectView


app_name = 'acco'

urlpatterns = [
    # path('', RedirectView.as_view(url='login/')),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup_success/', SignSuccessView.as_view(), name='signup_success'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
]

entry_app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import hello_world, world
from .views import ListEntryView, DetailEntryView, CreateEntryView, UserView, UpdateEntryView, DeleteEntryView

urlpatterns = [
    path('hello/', hello_world, name='hello_2'),
    path('world/', world, name='world'),
    path('', ListEntryView.as_view(), name='list_entry'),
    path('ent/<int:pk>/detail/', DetailEntryView.as_view(), name= 'detail_entry'),
    path('entry/create/', CreateEntryView.as_view(), name='create_entry'),
    path('user/<int:user>/entries/', UserView.as_view(), name='user_list'),
    path('entry/<int:pk>/update/', UpdateEntryView.as_view(), name='update_entry'),
    path('entry/<int:pk>/delete/', DeleteEntryView.as_view(), name='delete_entry'),
]

entrypro/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import hello_world

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello_world, name='hello'),
    path('', include('entry_app.urls')),
    path('account/', include('acco.urls')),
]

acco/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class AccountsUser(AbstractUser):
    pass

entry_app/models.py
from django.db import models
from acco.models import AccountsUser

# Create your models here.

class ModelApp(models.Model):
    t_title = models.CharField(max_length=10)
    t_text = models.CharField(max_length=100)
    user = models.ForeignKey(AccountsUser, on_delete=models.CASCADE)

acco/forms.py
from django.contrib.auth.forms import UserCreationForm
from  .models import AccountsUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = AccountsUser
        fields = ('username', 'email', 'password1', 'password2')

acco/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

# Create your views here.
class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'signup.html'
    success_url = reverse_lazy('acco:signup_success')

    def form_valid(self, form):
        user = form.save()
        self.object = user
        return super().form_valid(form)

class SignSuccessView(TemplateView):
    template_name = 'signup_success.html'

entry_app/views.py
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import ModelApp
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied


def hello_world(request):
    return HttpResponse('<h2>hello ザ　わーるど！ フロムapp</h2>')

def world(request):
    return HttpResponse('<h2>World! フロムapp</h2>')

class ListEntryView(ListView):
    template_name = 'entry/entry_model_list.html'
    model = ModelApp

class DetailEntryView(DetailView):
    template_name = 'entry/entry_model_detail.html'
    model = ModelApp

class CreateEntryView(LoginRequiredMixin, CreateView):
    template_name = 'entry/entry_create.html'
    model = ModelApp
    fields = ['t_title', 't_text']
    success_url = reverse_lazy('list_entry')

    def form_valid(self, form):
        entry = form.save(commit=False)
        entry.user = self.request.user
        entry.save()
        return super().form_valid(form)

class UserView(LoginRequiredMixin,ListView):
    template_name = 'entry/entry_model_list.html'
    paginate_by = 9

    def get_queryset(self):
        user_id = self.kwargs['user']
        user_list = ModelApp.objects.filter(user=user_id)
        return user_list

class UpdateEntryView(LoginRequiredMixin, UpdateView):
    template_name = 'entry/entry_update.html'
    model = ModelApp
    fields = ['t_title', 't_text']
    success_url = reverse_lazy('list_entry')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        if obj.user != self.request.user:
            raise PermissionDenied

        return obj

class DeleteEntryView(LoginRequiredMixin, DeleteView):
    template_name = 'entry/entry_delete.html'
    model = ModelApp
    success_url = reverse_lazy('list_entry')

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)

        if obj.user != self.request.user:
            raise PermissionDenied

        return obj

entrypro/views.py
from django.http import HttpResponse

def hello_world(request):
    return HttpResponse('<h2>hello ザ　わーるど！</h2>')

acco/templates/login.html
{% extends 'base.html' %}
{% block title %}ログイン{% endblock title %}

{% block content %}
{% if form.errors %}
  <P style="color:orange">ユーザー名とパスワードが一致しません</P>
{% endif %}
{% if user.is_authenticated %}
  <p>既にログインしています。</p>
{% else %}
  <form method="post">
    {% csrf_token %}
    <h1>ログインページ</h1>

    <label for="id_username">ユーザー名</label>
    <input type="text" name="username" id="id_username">
    <label for="id_password">パスワード</label>
    <input type="password" name="password" id="id_password">

    <input type="submit" value="ログイン">

  </form>
{% endif %}
{% endblock content %}

acco/templates/logout.html
{% extends 'base.html' %}
{% block title %}ログアウト{% endblock title %}
{% block content %}
<h3>ログアウトしました</h3>
{% endblock content %}

acco/templates/signup.html
{% extends 'base.html' %}
{% block title %}新規登録ページ{% endblock title %}

{% block content %}
  <h2>ユーザー登録フォーム</h2>
  <form method="post" class="p-4 m-4 bg-light border">
    {% csrf_token %}
    {% for field in form %}
      <div>
        {{ field.label_tag }}<br>
        {{ field }}
      </div>
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    {% endfor %}

    <input type="submit" value="登録" class="btn btn-primary">
  </form>
{% endblock content %}

acco/templates/signup_success.html
{% extends 'base.html' %}
{% block title %}ユーザー登録{% endblock title %}
{% block content %}
<h2>登録が完了しました</h2>
{% endblock content %}

entry_app/templates/entry/entry_create.html
{% extends 'base.html' %}
{% block title %}投稿フォーム{% endblock title %}

{% block content %}
  <h2>投稿フォーム</h2>
  <form method="post" class="p-4 m-4 bg-light border">
    {% csrf_token %}
    {% for field in form %}
      <div>
      {{ field.label_tag }}<br>
      {{ field }}
      </div>
      {% for error in field.errors %}
        <p style="color:orange">{{ error }}</p>
      {% endfor %}
    {% endfor %}

    <input type="submit" value="投稿" class="btn btn-primary">
  </form>
{% endblock content %}

entry_app/templates/entry/entry_delete.html
{% extends 'base.html' %}
{% block title %}削除ページ{% endblock title %}

{% block content %}
    <form method="post" class="p-4 m-4 bg-light border">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">{{ object.t_title }}を削除する</button>
    </form>
{% endblock content %}

entry_app/templates/entry/entry_model_detail.html
{% extends 'base.html' %}
{% block title %}詳細ページ{% endblock title %}
{% block content %}
    <div class="card mb-1 ms-2" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">{{ object.t_title }}</h5>
        <p class="card-text">{{ object.t_text }}</p>
        <span class="text-muted small">（投稿者：{{object.user.username}}）</span>
        {% if request.user == object.user %}
          <a href="{% url 'update_entry' object.pk %}" class="btn btn-dark">修正</a>
          <a href="{% url 'delete_entry' object.pk %}" class="btn btn-danger">削除</a>
        {% endif %}
      </div>
    </div>
{% endblock content %}

entry_app/templates/entry/entry_model_list.html
{% extends 'base.html' %}
{% block title %}学習ノートアプリ一覧{% endblock %}
{% block content %}
    <h2>～ 投稿一覧 ～</h2>
    {% if not object_list %}
        <p>※{{ user.username }}さんの投稿はまだありません。</p>
    {% endif %}
    <div class="list-group px-2">
        <ul>
            {% for entry in object_list %}
                <li class="mb-2">
                    <a href="{% url 'detail_entry' entry.pk %}"
                       class="list-group-item list-group-item-action w-80">{{entry.t_title}}
                        <span class="text-muted small">（投稿者：{{entry.user.username}}）</span>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

entry_app/templates/entry/entry_update.html
{% extends 'base.html' %}
{% block title %}投稿の修正フォーム{% endblock title %}

{% block content %}
    <h2>投稿の修正フォーム</h2>
    <form method="post" class="p-4 m-4 bg-light border">
        {% csrf_token %}
        {% for field in form %}
            <div>
            {{ field.label_tag }}<br>
            {{ field }}
            </div>
            {% for error in field.errors %}
                <p style="color:orange">{{ error }}</p>
            {% endfor %}
        {% endfor %}

        <input type="submit" value="修正" class="btn btn-primary">
    </form>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
      <title>{% block title %}{% endblock %}|学習ノート</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid"><a class="navbar-brand" href="{% url 'list_entry' %}">学習ノート</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'user_list' user.pk %}">{{user.username}}の投稿一覧</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'create_entry' %}">投稿フォーム</a>
                        </li>
                    {% endif %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown"
                               aria-expanded="false">アカウント関連
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'acco:signup' %}">新規ユーザー登録</a></li>
                                {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'acco:logout' %}">ログアウト</a></li>
                                {% else %}
                                <li><a class="dropdown-item" href="{% url 'acco:login' %}">ログイン</a></li>
                                {% endif %}
                            </ul>
                        </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>